### ISSUE TITLE
视图错位

### ISSUE THREAD

**Issue by xygkevin** [SilenceLove/HXPhotoPickerObjC#2]
![IMG_5356](https://github.com/SilenceLove/HXPhotoPickerObjC/assets/19592642/141960b1-1267-466c-b65c-94175607475a)

**Comment by xygkevin** [comment]
如图，顶部导航的视图向右侧偏移

真机线上环境 iPhone13 proMax

**Comment by xygkevin** [comment]
系统是iOS17.0.3

**Comment by SilenceLove** [comment]
可以提个pr，我合并一下

**Comment by xygkevin** [comment]
使用Xcode15运行没有问题了，先不管吧
